2025-04-16 10:36:35,485 INFO    MainThread:1141666 [wandb_setup.py:_flush():68] Current SDK version is 0.19.2
2025-04-16 10:36:35,485 INFO    MainThread:1141666 [wandb_setup.py:_flush():68] Configure stats pid to 1141666
2025-04-16 10:36:35,485 INFO    MainThread:1141666 [wandb_setup.py:_flush():68] Loading settings from /home/ubuntu/.config/wandb/settings
2025-04-16 10:36:35,486 INFO    MainThread:1141666 [wandb_setup.py:_flush():68] Loading settings from /data/temp_Jongann/SimJEB_GATr/baseline_EGNN/wandb/settings
2025-04-16 10:36:35,486 INFO    MainThread:1141666 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-04-16 10:36:35,487 INFO    MainThread:1141666 [wandb_init.py:_log_setup():523] Logging user logs to /data/temp_Jongann/SimJEB_GATr/baseline_EGNN/wandb/run-20250416_103635-xx0nt2re/logs/debug.log
2025-04-16 10:36:35,488 INFO    MainThread:1141666 [wandb_init.py:_log_setup():524] Logging internal logs to /data/temp_Jongann/SimJEB_GATr/baseline_EGNN/wandb/run-20250416_103635-xx0nt2re/logs/debug-internal.log
2025-04-16 10:36:35,489 INFO    MainThread:1141666 [wandb_init.py:init():641] calling init triggers
2025-04-16 10:36:35,490 INFO    MainThread:1141666 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0005, 'architecture': 'EGNN', 'dataset': 'SimJEB', 'epochs': 1000}
2025-04-16 10:36:35,490 INFO    MainThread:1141666 [wandb_init.py:init():674] starting backend
2025-04-16 10:36:35,708 INFO    MainThread:1141666 [wandb_init.py:init():678] sending inform_init request
2025-04-16 10:36:35,716 INFO    MainThread:1141666 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-16 10:36:35,717 INFO    MainThread:1141666 [wandb_init.py:init():693] backend started and connected
2025-04-16 10:36:35,727 INFO    MainThread:1141666 [wandb_init.py:init():786] updated telemetry
2025-04-16 10:36:35,764 INFO    MainThread:1141666 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-04-16 10:36:36,219 ERROR   MainThread:1141666 [wandb_init.py:init():845] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-04-16 10:36:36,219 ERROR   MainThread:1141666 [wandb_init.py:init():1299] error in wandb.init()
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/JHL_env/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/JHL_env/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 851, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-04-16 10:36:36,272 WARNING MsgRouterThr:1141666 [router.py:message_loop():75] message_loop has been closed
